name: build-to-dockerhub
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub Build And Push Release Version
        id: buildAndPushImage
        uses: Abhishek-070/Dockerhub-Build-Push@v1.0
        with:
          registry_url: 'docker.io'
          repository_name: 'erikcc02/echo-server'
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_version: ${{ github.event.release.tag_name }}
          docker_file: '.'

      - name: DockerHub Build And Push Latest
        id: buildAndPushImageLatest
        uses: Abhishek-070/Dockerhub-Build-Push@v1.0
        with:
          registry_url: 'docker.io'
          repository_name: 'erikcc02/echo-server'
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_version: latest
          docker_file: '.'

      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"